### POST reset-password
POST http://localhost:3000/api/auth/reset-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
x-platform: web
Content-Type: application/json

{
  "oldPassword": "password",
  "newPassword": "newPassword"
}

### POST forgot-password
POST http://localhost:3000/api/auth/forgot-password
x-platform: web
Content-Type: application/json

{
  "email": "email"
}

### POST set-new-password
POST http://localhost:3000/api/auth/set-new-password
x-platform: web
Content-Type: application/json

{
  "token": "token",
  "newPassword": "newPassword"
}
